FROM openthoughts.artifactoryonline.com/openthoughts/ape-dev-docker-base
MAINTAINER Time Inc <anilbhatb@openthoughts.in>

# copy application files
ADD  build/distributions/dam-ingest-client-1-SNAPSHOT.tar  /app/

